CREATE DATABASE IF NOT EXISTS tokoaruna;
USE tokoaruna;

CREATE TABLE pesanan (
  id INT(11) AUTO_INCREMENT PRIMARY KEY,
  nama VARCHAR(100) NOT NULL,
  produk VARCHAR(100) NOT NULL,
  jumlah INT(10) NOT NULL,
  alamat TEXT NOT NULL,
  telepon VARCHAR(20) NOT NULL,
  tanggal_pesan TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
